# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'
inhibit_all_warnings!

target 'LLClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LLClient
  pod 'SwiftyBeaver'
  #5.5以上版本在iOS 12系统会有问题参考https://www.jianshu.com/p/b0bf3f7256cb
  pod 'Alamofire', '~> 5.4.4'
  pod 'MJRefresh', '3.2.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'LLAccount', :path => './local_pods/LLAccount'
  pod 'LLMain', :path => './local_pods/LLMain'
  pod 'LLNetwork', :path => './local_pods/LLNetwork'
  pod 'LLCommon', :path => './local_pods/LLCommon'

  target 'LLClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LLClientUITests' do
    # Pods for testing
  end

end
