# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'BYRClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BYRClient
  pod 'Masonry'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 7.0'

  target 'BYRClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BYRClientUITests' do
    # Pods for testing
  end

end
